In [1]:
import sqlite3
import numpy as np
import pandas as pd

In [2]:
conn = sqlite3.connect("../scraper/data/ads_storage.db")
cursor = conn.cursor()

In [3]:
query = '''SELECT * FROM ads_appartments'''
cursor.execute(query)
rows = cursor.fetchall()

columns = [description[0] for description in cursor.description]

ads_appartments = pd.DataFrame(data=rows, columns=columns)
ads_appartments.head()

,hash_id,title,img_url,link,neighbourhood,type_of_estate,total_price_eur,price_m2_eur,price_m2_bgn,size_m2,...,near_public_transport,furnished,includes_parking,new_building,akt16,energy_class,potreblenie,broker_commision,additional_notes,extras
0,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/web/files/obiavi/5945620...,https://www.imoti.net/bg/obiava/prodava/sofia/...,Овча Купел,жилище,92512.0,1888.0,3692.13,49.0,...,1,0,1,0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен; Паркомясто
1,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/web/files/obiavi/5883830...,https://www.imoti.net/bg/obiava/prodava/sofia/...,Фондови Жилища,жилище,95975.0,1745.0,3413.81,55.0,...,1,1,0,0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,
2,b6c286ce2e6de97589316b15c742cce2b09e5b655ba169...,"Имот - продава Двустаен апартамент, в София, Л...",https://www.imoti.net/web/files/obiavi/6176496...,https://www.imoti.net/bg/obiava/prodava/sofia/...,Левски,жилище,98022.0,1581.0,3091.47,62.0,...,1,0,0,0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен
3,9a0fa18467acc9749700e245657c32afdf868653c06d87...,"Имот - продава Двустаен апартамент, в София, К...",https://www.imoti.net/web/files/obiavi/6157158...,https://www.imoti.net/bg/obiava/prodava--v-str...,Карпузица,жилище,98560.0,2240.0,4380.08,44.0,...,1,1,0,0,NaN,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,
4,d4bc76fbc196bf3af9ccb2d2caae76b3b17f5980083ba3...,"Имот - продава Двустаен апартамент, в София, Л...",https://www.imoti.net/web/files/obiavi/6236152...,https://www.imoti.net/bg/obiava/prodava/sofia/...,Левски,жилище,98616.0,1761.0,3443.48,56.0,...,0,1,0,0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,

In [4]:
ads_appartments.info()

<class 'pandas.DataFrame'>
RangeIndex: 5488 entries, 0 to 5487
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   hash_id                5488 non-null   str
 1   title                  5488 non-null   str
 2   img_url                5488 non-null   str
 3   link                   5488 non-null   str
 4   neighbourhood          5393 non-null   str
 5   type_of_estate         5488 non-null   str
 6   total_price_eur        5400 non-null   float64
 7   price_m2_eur           5406 non-null   float64
 8   price_m2_bgn           5406 non-null   float64
 9   size_m2                5401 non-null   float64
 10  nr_of_rooms            5211 non-null   float64
 11  description            5488 non-null   str
 12  appartment_floor       5322 non-null   float64
 13  total_floors           5488 non-null   int64
 14  is_first_floor         5322 non-null   float64
 15  is_last_floor          5488 non-null   int64
 16  near_public_transport  5488 non-null   int64
 17  furnished              5488 non-null   int64
 18  includes_parking       5488 non-null   int64
 19  new_building           5488 non-null   int64
 20  akt16                  4992 non-null   float64
 21  energy_class           5354 non-null   str
 22  potreblenie            5354 non-null   str
 23  broker_commision       5387 non-null   float64
 24  additional_notes       5407 non-null   str
 25  extras                 5488 non-null   str
dtypes: float64(9), int64(6), str(11)
memory usage: 1.1 MB

In [6]:
ads_appartments[ads_appartments["neighbourhood"] == "дружба 2"]

Empty DataFrame
Columns: [hash_id, title, img_url, link, neighbourhood, type_of_estate, total_price_eur, price_m2_eur, price_m2_bgn, size_m2, nr_of_rooms, description, appartment_floor, total_floors, is_first_floor, is_last_floor, near_public_transport, furnished, includes_parking, new_building, akt16, energy_class, potreblenie, broker_commision, additional_notes, extras]
Index: []

[0 rows x 26 columns]

In [5]:
ads_appartments["link"].tolist()

['https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/ednostaen/6176507/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/fondovi-jilishta/ednostaen/5883830/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-levski/dvustaen/6176496/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/karpuzica/dvustaen/6157158/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-levski/dvustaen/6206616/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/gorubljane/dvustaen/6107931/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-levski/dvustaen/6206618/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/dvustaen/6176497/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-studentski-grad/ednostaen/6181566/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/drujba-2/ednostaen/6213577/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/dvustaen/6193676/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/mladost-2/ednostaen/6115703/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/dvustaen/6193677/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/dvustaen/6109527/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/dvustaen/6202594/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6181567/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/fondovi-jilishta/dvustaen/6163797/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/vitosha/tristaen/6194561/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/dvustaen/6195602/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/gorubljane/tristaen/6119895/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-mladost-1/ednostaen/6191225/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/dvustaen/6213202/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-2/tristaen/6113869/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/sofia-center/dvustaen/5783910/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/manastirski-livadi/ofis/5955309/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/krystova-vada/dvustaen/6209931/?sid=icNBCK&page=1',
 'https://www.imoti.net/bg/obiava/prodava/sofia/reduta/dvustaen/6177224/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/krasna-poljana/tristaen/6184706/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/manastirski-livadi/dvustaen/5977479/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/dvustaen/6185141/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/tristaen/6212373/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/mladost-1a/dvustaen/6212173/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/suha-reka/tristaen/6182356/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/poligona/dvustaen/6212632/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/tristaen/6213606/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/nadejda-2/tristaen/6198256/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-mladost-1/chetiristaen/6196623/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/obelja-1/tristaen/6165103/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/tristaen/6176564/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/tristaen/6213633/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/belite-brezi/dvustaen/6199027/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/pancharevo/tristaen/6102475/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/dvustaen/6207292/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/slatina/dvustaen/6198504/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/banishora/tristaen/6173154/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/tristaen/6213555/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/tristaen/6146198/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/knjajevo/dvustaen/5840040/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/krystova-vada/dvustaen/6200959/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/dianabad/dvustaen/6018722/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/tristaen/6172857/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/tristaen/6146200/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/oborishte/tristaen/6129179/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/mladost-2/tristaen/6191049/?sid=icNBCK&page=2',
 'https://www.imoti.net/bg/obiava/prodava/sofia/suha-reka/mezonet/6129874/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel-1/tristaen/6084423/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/ovcha-kupel-1/dvustaen/5958083/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/dianabad/tristaen/6206005/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/mladost-4/dvustaen/5766356/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/chetiristaen/6213615/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/manastirski-livadi/tristaen/5856001/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/chetiristaen/6172854/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/manastirski-livadi/tristaen/6181558/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/drujba-2/dvustaen/6212934/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/drujba-1/tristaen/6176604/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/chetiristaen/6213609/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-studentski-grad/dvustaen/6209274/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/manastirski-livadi/tristaen/5977482/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/banishora/tristaen/6205738/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/ofis/6091168/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/dragalevci/dvustaen/5995282/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/dvustaen/6192324/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/bojana/tristaen/6084671/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/pancharevo/tristaen/6102476/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/ovcha-kupel/tristaen/5672388/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-mladost-1/tristaen/6140569/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/vitosha/tristaen/6117959/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/mladost-3/dvustaen/6135906/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vrybnica-2/dvustaen/6103365/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/drujba-2/tristaen/6212938/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/vitosha/tristaen/6119358/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-centyr-bul-al-stambolijski/tristaen/6211135/?sid=icNBCK&page=3',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/tristaen/6128819/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/mladost-3/dvustaen/6142911/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/tristaen/6213273/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/mladost-1a/tristaen/6177104/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/tristaen/6212063/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/krystova-vada/tristaen/6210675/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/mladost-3/tristaen/6136700/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/drujba-2/tristaen/6212940/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/bojana/dvustaen/6151276/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/oborishte/tristaen/6088541/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/tristaen/6019209/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/chetiristaen/6181123/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/banishora/chetiristaen/6200941/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/gorna-banja/tristaen/6055021/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lagera/tristaen/6147251/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/dianabad/tristaen/5805229/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/krystova-vada/tristaen/5745831/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/gorna-banja/tristaen/6055022/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/tristaen/6210701/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/bul-vasil-levski/mnogostaen/6212855/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/tristaen/6128211/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/tristaen/6202140/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/medicinska-akademija/tristaen/6147115/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/tristaen/6119363/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/krystova-vada/chetiristaen/6137789/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/7-mi-11-ti-kilometyr/tristaen/6208048/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/zavedenie/6061420/?sid=icNBCK&page=4',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/dragalevci/chetiristaen/5994904/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/medicinska-akademija/zavedenie/6072956/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/bojana/mnogostaen/5703272/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/tristaen/6193989/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/7-mi-11-ti-kilometyr/tristaen/6209798/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/krystova-vada/chetiristaen/5699085/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/chetiristaen/6123863/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/kambanite/chetiristaen/6191525/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/kriva-reka/tristaen/6029079/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/lozenec/tristaen/5750082/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/tristaen/5566759/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/doktorski-pametnik/tristaen/6212289/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/7-mi-11-ti-kilometyr/tristaen/6209054/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-centyr-idealen-centyr/etaj-ot-kashta/6136011/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/zavedenie/6030574/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/chetiristaen/6074871/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/manastirski-livadi/ofis/6123791/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/vitosha/mnogostaen/6108225/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/simeonovo/sgrada/6105588/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/7-mi-11-ti-kilometyr/mnogostaen/6208049/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/sofia-center/tyrgovski-obekt/5975955/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/sgrada/5790589/?sid=icNBCK&page=5',
 'https://www.imoti.net/bg/obiava/prodava/sofia/levski-g/sgrada/6202567/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/bojana/dvustaen/6195711/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/ofis/6212518/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/gara-iskyr/sklad/6142314/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/myrchaevo/zemedelski-imot/5998667/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/sklad/6156444/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ul-car-asen/tyrgovski-obekt/6195717/?sid=icNBCK&page=6',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-centyr/ofis/6107706/?sid=icNBCK&page=7',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-studentski-grad/ofis/6089536/?sid=icNBCK&page=7',
 'https://www.imoti.net/bg/obiava/prodava/sofia/jeljava/zemedelski-imot/5733100/?sid=icNBCK&page=7',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozen/zemedelski-imot/5692552/?sid=icNBCK&page=8',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/lulin-8/sgrada/5682251/?sid=icNBCK&page=8',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/razsadnika/sklad/5792376/?sid=icNBCK&page=8',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/sklad/6163979/?sid=icNBCK&page=8',
 'https://www.imoti.net/bg/obiava/prodava/sofia/karpuzica/zemedelski-imot/4180701/?sid=icNBCK&page=8',
 'https://www.imoti.net/bg/obiava/prodava/sofia/suhodol/zemedelski-imot/3341264/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/malinova-dolina/ednostaen/6150483/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/kremikovci/zemedelski-imot/3229140/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/novi-iskyr/zemedelski-imot/6053885/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/botunec/dvustaen/6083784/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6160853/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-10/ofis/6102234/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/karpuzica/zemedelski-imot/4180705/?sid=icNBCK&page=9',
 'https://www.imoti.net/bg/obiava/prodava/sofia/jeleznica/zemedelski-imot/5660006/?sid=icNBCK&page=10',
 'https://www.imoti.net/bg/obiava/prodava/sofia/tyrgovski-obekt/6185389/?sid=icNBCK&page=10',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/ednostaen/6060012/?sid=icNBCK&page=10',
 'https://www.imoti.net/bg/obiava/prodava/sofia/bojana/promishlen-imot/6203561/?sid=icNBCK&page=11',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/ednostaen/6148303/?sid=icNBCK&page=11',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofija-goce-delchev/sklad/5601968/?sid=icNBCK&page=11',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/chepinci/zemedelski-imot/3319447/?sid=icNBCK&page=11',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/chepinci/zemedelski-imot/3319446/?sid=icNBCK&page=11',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozen/vila/6103980/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava/sofia/orlandovci/dvustaen/5950276/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/ednostaen/5940288/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava/sofia/suha-reka/ednostaen/5929572/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava/sofia/zona-b19/ednostaen/6074818/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava/sofia/plana/zemedelski-imot/5731503/?sid=icNBCK&page=12',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/lulin-8/tyrgovski-obekt/6158526/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6151445/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6151446/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/dianabad/ofis/6141765/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/novi-iskyr/zemedelski-imot/6054002/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel-2/ofis/6075822/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/novi-iskyr/zemedelski-imot/5899963/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/dvustaen/6206699/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/ofis/5750060/?sid=icNBCK&page=13',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lozenec/tyrgovski-obekt/6167075/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/banishora/dvustaen/6114574/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/banishora/ednostaen/6068986/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/levski-g/ednostaen/6138414/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6183428/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-10/ednostaen/6176433/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/lulin-10/ednostaen/6047641/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/malinova-dolina/ednostaen/6151447/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-centyr/dvustaen/6078557/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/dvustaen/5965199/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/chepinci/zemedelski-imot/3553950/?sid=icNBCK&page=14',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/dvustaen/5927173/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/sofia-center/ofis/5770533/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/lulin-5/ednostaen/6207804/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/kokaljane/zemedelski-imot/6097472/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/obelja-1/ednostaen/6213312/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/dolni-bogrov/zemedelski-imot/6125317/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava/sofia/poligona/ofis/6089331/?sid=icNBCK&page=15',
 'https://www.imoti.net/bg/obiava/prodava--v-stroej/sofia/lulin-8/ofis/6186232/?sid=icNBCK&page=15',