In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()

# Fetch all data
cursor.execute("SELECT * FROM ads_raw")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(rows, columns=columns)

# print(f"Total ads: {len(df)}")

conn.close()
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,scraped_at,last_updated
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:14.999578,2026-02-15 16:58:14.999578
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008348,2026-02-15 16:58:15.008348
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008562,2026-02-15 16:58:15.008562
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008903,2026-02-15 16:58:15.008903
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.009103,2026-02-15 16:58:15.009103

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
quuery = '''select *
from ads_storage.COLUMNS
where TABLE_NAME=ads_raw'''

cursor.execute(quuery)

OperationalError: no such table: ads_storage.COLUMNS

In [2]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute("SELECT hash_id, link, extras FROM ads_raw WHERE extras IS NOT NULL")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()
conn.close()
# Convert to DataFrame
df = pd.DataFrame(rows, columns=columns)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2022 entries, 0 to 2021
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   hash_id  2022 non-null   str
 1   link     2022 non-null   str
 2   extras   2022 non-null   str
dtypes: str(3)
memory usage: 47.5 KB

In [3]:
df["extras"].unique().tolist()

['ТЕЦ',
 'Регулация',
 '',
 'Необзаведен; Паркомясто',
 'Необзаведен',
 'Обзаведен',
 'ТЕЦ; Асансьор; До метростанция - до 10 мин.пеш',
 'ТЕЦ; Асансьор',
 'Асансьор',
 'Асансьор; Ново строителство',
 'EMPTY',
 'Регулация; За жилищно строителство',
 'Необзаведен; Офис сграда; Интернет връзка; Ново строителство',
 'Ново строителство; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Паркомясто; Ток; Водопровод; Канализация; Гараж; Асансьор; Двор; Ново строителство; Лукс',
 'Климатик; Паркомясто; Ток; Водопровод; Гараж; Асансьор; Ново строителство; Лукс',
 'Локал. отопление; Необзаведен; Асансьор; Ново строителство; Лукс',
 'Телефон; Обзаведен; ТЕЦ; Асансьор; Паркомясто; До метростанция - до 10 мин.пеш',
 'Двор; Ново строителство',
 'Локал. отопление; Обзаведен; ТЕЦ; Асансьор; До метростанция - до 10 мин.пеш',
 'ТЕЦ; Асансьор; Ново строителство',
 'ТЕЦ; Гараж; Асансьор',
 'Обзаведен; ТЕЦ; Асансьор; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Асансьор',
 'Климатик; Ток; Водопровод; Асансьор; Ново строителство; Лукс',
 'Необзаведен; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Климатик; Охрана; Паркомясто; Ток; Водопровод; Канализация; ТЕЦ; Гараж; Асансьор; Лукс',
 'ТЕЦ; Гараж; Асансьор; Ново строителство; Лукс; До метростанция - до 10 мин.пеш',
 'Обзаведен; ТЕЦ; Асансьор; Разрешено за дом. любимец; До метростанция - до 10 мин.пеш; За бежанци',
 'Локал. отопление; Необзаведен; ТЕЦ; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Обзаведен; ТЕЦ; Асансьор; Ново строителство; Паркомясто',
 'Асансьор; Ново строителство; Паркомясто',
 'Локал. отопление; Ток; Водопровод; Асансьор; Ново строителство; Фитнес център; Зала; Лукс',
 'Ново строителство',
 'WC; Ново строителство',
 'Обзаведен; ТЕЦ; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Ток; Водопровод; Асансьор; Ново строителство; Лукс',
 'Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Ток; Водопровод; Асансьор; Ново строителство; Лукс',
 'Ток; Водопровод; ТЕЦ; Асансьор; Ново строителство; Лукс',
 'Необзаведен; ТЕЦ; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'ТЕЦ; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Ново строителство; Лукс',
 'Необзаведен; Гараж; Асансьор',
 'Обзаведен; Климатик; Асансьор',
 'Локал. отопление; Ток; Водопровод; Канализация; Асансьор; Ново строителство; Лукс',
 'Локал. отопление; Ток; Водопровод; Гараж; WC; Двор; Ново строителство; Лукс',
 'Паркомясто; Ток; Водопровод; Канализация; Асансьор; Ново строителство; Лукс',
 'Обзаведен; Климатик; Паркомясто; Ток; Водопровод; Канализация; Гараж; Асансьор; Двор; Ново строителство; Фитнес център; Зала; Лукс',
 'Обзаведен; Гараж; Асансьор',
 'Обзаведен; Климатик; Паркомясто; Ток; Водопровод; Канализация; Асансьор; Двор; Ново строителство; Лукс',
 'Телефон; Интернет връзка; Охрана; Паркомясто; Ток; Водопровод; Канализация; ТЕЦ; Гараж; WC; Басейн; Асансьор; Двор; Ново строителство; Фитнес център; Зала; Лукс',
 'Климатик; WC',
 'Локал. отопление; Оборудване; Склад; WC',
 'Обзаведен; Климатик; Ток; Водопровод; Асансьор; Ново строителство; Лукс',
 'Локал. отопление; Паркомясто; Ток; Водопровод; Канализация; Гараж; WC; Двор; Ново строителство; Лукс',
 'Телефон; Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Гараж; Асансьор; Двор; Ново строителство; Лукс',
 'Необзаведен; Климатик; Гараж; Асансьор',
 'Паркомясто; Ток; Водопровод; Канализация; ТЕЦ; Гараж; Асансьор; Ново строителство; Лукс',
 'Необзаведен; ТЕЦ; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс; До метростанция - до 10 мин.пеш',
 'Необзаведен; ТЕЦ; Асансьор; До метростанция - до 10 мин.пеш',
 'Необзаведен; Двор; Паркомясто; До метростанция - до 10 мин.пеш',
 'Ток; Водопровод; Канализация; Лукс',
 'Гараж; Асансьор',
 'Охрана; Асансьор; Ново строителство; Паркомясто',
 'Ток; Водопровод; WC; Лукс',
 'Обзаведен; Паркомясто; Асансьор; Лукс',
 'Асансьор; Ново строителство; Лукс',
 'Необзаведен; Гараж; Двор; Лукс',
 'Локал. отопление; Лукс',
 'Обзаведен; Гараж; Двор; Фризьорски салон; Козметичен салон; Лукс',
 'Обзаведен; Климатик; Охрана; Гараж; Фитнес зала; Асансьор; Лукс',
 'Обзаведен; Гараж; Двор; Лукс',
 'Обзаведен; Асансьор',
 'Локал. отопление; Паркомясто; Товарен вход',
 'Подземен',
 'Заден',
 'Равен',
 'Преден',
 'Локал. отопление; Подземен',
 'Регулация; За обезщетение',
 'Заден; Надземен',
 'За жилищно строителство',
 'Надземен',
 'Равен; За промишлено строителство; Делим',
 'Подземен; Надземен',
 'Равен; За промишлено строителство',
 'Равен; За жилищно строителство; Делим; Подходящо за живеене',
 'Регулация; Ток; Водопровод; За жилищно строителство; Подходящо за живеене',
 'Ток; Водопровод; За жилищно строителство; Подходящо за живеене',
 'Необзаведен; Асансьор; Ново строителство',
 'Локал. отопление',
 'Водопровод',
 'Паркомясто',
 'За жилищно строителство; Подходящо за живеене',
 'Ток; За обезщетение; За жилищно строителство',
 'Гараж; Ново строителство',
 'Равен; Делим; Подходящо за живеене',
 'Локал. отопление; Надземен',
 'Равен; Делим',
 'Локал. отопление; WC; Ново строителство; До метростанция - до 10 мин.пеш',
 'Канализация',
 'Оборудване; WC',
 'Ток; За жилищно строителство; Подходящо за живеене',
 'WC',
 'ТЕЦ; Подземен',
 'Локал. отопление; WC',
 'WC; До метростанция - до 10 мин.пеш',
 'Регулация; Ток; Водопровод; Канализация; Равен',
 'Регулация; Водопровод',
 'Необзаведен; Ток; Водопровод; Канализация',
 'Ток',
 'Ток; Водопровод; Канализация; Гараж',
 'ТЕЦ; Заден; Надземен',
 'Регулация; Ток; Водопровод',
 'Регулация; ВИЗА; Ток; За жилищно строителство',
 'Регулация; Равен; За жилищно строителство',
 'Лукс',
 'Регулация; Ток; Водопровод; За жилищно строителство',
 'ТЕЦ; WC; Подходящо за живеене; До метростанция - до 10 мин.пеш',
 'Регулация; За промишлено строителство',
 'Необзаведен; Ток; Водопровод; Канализация; Ново строителство',
 'Офис сграда; ТЕЦ; Асансьор',
 'Локал. отопление; Телефон; Обезопасен; Офис сграда; Интернет връзка; Асансьор; Лукс; До метростанция - до 10 мин.пеш',
 'Обзаведен; Фризьорски салон; Козметичен салон; Спа център; До метростанция - до 10 мин.пеш',
 'Необзаведен; Гараж; Асансьор; Ново строителство',
 'Климатик; Интернет връзка; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Необзаведен; Гараж; Асансьор',
 'Локал. отопление; Необзаведен; Офис сграда',
 'Необзаведен; Климатик; Ток; Водопровод; Канализация; Ново строителство',
 'За промишлено строителство',
 'ТЕЦ; WC; Ново строителство; До метростанция - до 10 мин.пеш',
 'Необзаведен; Асансьор',
 'Необзаведен; Ток; Водопровод; Канализация; ТЕЦ; WC; Асансьор; Ново строителство',
 'Ток; Водопровод; За жилищно строителство',
 'Локал. отопление; Необзаведен; Ново строителство',
 'Климатик; Паркомясто; Канализация; Гараж; Асансьор; Ново строителство; Лукс',
 'Преден; Заден; Подземен',
 'Регулация; Равен; За обезщетение; За жилищно строителство; За промишлено строителство',
 'Локал. отопление; Необзаведен; Гараж; Асансьор; Ново строителство; Паркомясто',
 'Необзаведен; Асансьор; Паркомясто',
 'Климатик; Ток; Ново строителство',
 'Локал. отопление; Ток; Водопровод; Асансьор; Ново строителство',
 'Ток; Водопровод',
 'Обзаведен; Климатик; Офис сграда; Интернет връзка; Ток; Водопровод; Канализация',
 'Необзаведен; ТЕЦ; Асансьор; Подходящо за живеене; До метростанция - до 10 мин.пеш',
 'Климатик; До метростанция - до 10 мин.пеш',
 'Обзаведен; Климатик; Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Двор; Ново строителство',
 'Локал. отопление; Обзаведен; Климатик; Офис сграда; Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Двор; Ново строителство',
 'Локал. отопление; Обзаведен; Климатик; Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Ново строителство',
 'Паркомясто; Ново строителство; Лукс',
 'Необзаведен; Паркомясто; Асансьор',
 'Обзаведен; Ток; Водопровод; Канализация; ТЕЦ; WC; Асансьор',
 'Интернет връзка; Водопровод; Канализация; Асансьор; Ново строителство',
 'Необзаведен; Ток; Водопровод; Канализация; Асансьор; Ново строителство',
 'Необзаведен; ТЕЦ; Асансьор',
 'Обзаведен; Паркомясто',
 'Ток; Водопровод; Асансьор; Ново строителство',
 'Обзаведен; ТЕЦ',
 'До метростанция - до 10 мин.пеш',
 'Необзаведен; Гараж; Асансьор; Паркомясто',
 'Локал. отопление; Заден; Надземен',
 'Климатик; Ток; Асансьор; Ново строителство',
 'Локал. отопление; Асансьор; Ново строителство; Паркомясто',
 'Локал. отопление; Обзаведен; ТЕЦ; Гараж; Асансьор; Паркомясто',
 'ТЕЦ; WC; Ново строителство; Подходящо за живеене',
 'Необзаведен; ТЕЦ; Ново строителство; До метростанция - до 10 мин.пеш',
 'Двор; Паркомясто',
 'Необзаведен; Ток; Водопровод; Канализация; WC; Асансьор; Ново строителство',
 'Ново строителство; Паркомясто',
 'Обзаведен; Асансьор; Ново строителство',
 'Необзаведен; ТЕЦ',
 'Необзаведен; ТЕЦ; Асансьор; Ново строителство',
 'Паркомясто; Ток; Водопровод; Канализация; ТЕЦ; Асансьор; Двор; Ново строителство',
 'Телефон; Паркомясто; ТЕЦ; WC; Ново строителство',
 'Необзаведен; Ток; Водопровод; Канализация; ТЕЦ; Гараж; Асансьор; Ново строителство',
 'Обзаведен; ТЕЦ; Асансьор',
 'ТЕЦ; Асансьор; Ново строителство; Паркомясто; До метростанция - до 10 мин.пеш',
 'Необзаведен; ТЕЦ; Ново строителство; Паркомясто; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Необзаведен; Обзаведен; Разрешено за дом. любимец',
 'ТЕЦ; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Интернет връзка; Ток; Водопровод; Канализация; Асансьор; Ново строителство',
 'Гараж; Асансьор; Ново строителство',
 'Локал. отопление; Ток; Асансьор; Ново строителство; Лукс',
 'Водопровод; ТЕЦ; Склад; WC; Асансьор',
 'Необзаведен; Гараж',
 'Ток; Водопровод; Канализация; ТЕЦ',
 'Необзаведен; Гараж; Паркомясто',
 'Необзаведен; ТЕЦ; Ново строителство',
 'Локал. отопление; Оборудване; WC',
 'Гараж; Асансьор; Паркомясто',
 'Регулация; ВИЗА; Ток; Водопровод; За жилищно строителство; Подходящо за живеене',
 'Локал. отопление; Необзаведен; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Ново строителство; Лукс',
 'ТЕЦ; Ново строителство',
 'Равен; За жилищно строителство; Подходящо за живеене',
 'Необзаведен; Ток; Канализация; WC; Асансьор; Ново строителство',
 'За жилищно строителство; На първа линия',
 'Локал. отопление; Товарен вход; WC; Трифазен ток; До метростанция - до 10 мин.пеш',
 'Двор; Разрешено за дом. любимец; Паркомясто',
 'Локал. отопление; Паркомясто; Ток; Водопровод; Ново строителство',
 'Регулация; ВИЗА; Ток; Водопровод; Канализация; Равен; За жилищно строителство',
 'Асансьор; До метростанция - до 10 мин.пеш',
 'Климатик; Водопровод; Канализация; Гараж; Асансьор; Ново строителство',
 'Необзаведен; Климатик; Асансьор; Ново строителство',
 'Необзаведен; Обезопасен; ТЕЦ; Фризьорски салон; Козметичен салон; Клиника; Кабинет; До метростанция - до 10 мин.пеш',
 'Локал. отопление; WC; Предназначение; Ново строителство',
 'Локал. отопление; Необзаведен; Гараж; Ново строителство; Паркомясто',
 'Климатик; Ток; Водопровод; Канализация; ТЕЦ; Ново строителство',
 'Обзаведен; Офис сграда; WC',
 'Двор',
 'Ток; Водопровод; Канализация; Асансьор; Ново строителство; Лукс',
 'Ток; Асансьор; Двор; Ново строителство',
 'Интернет връзка; До метростанция - до 10 мин.пеш',
 'Необзаведен; Гараж; Асансьор; Ново строителство; Паркомясто',
 'Необзаведен; ТЕЦ; Асансьор; Ново строителство; Паркомясто',
 'Ток; Ново строителство; Лукс',
 'Гараж; Асансьор; Ново строителство; Паркомясто',
 'Локал. отопление; Необзаведен; Гараж; Двор; Ново строителство; Паркомясто',
 'Обзаведен; Ток; Водопровод; Канализация; WC; Асансьор',
 'Телефон; Обзаведен; Интернет връзка; Водопровод; Канализация; ТЕЦ; WC',
 'Асансьор; Паркомясто',
 'Обзаведен; Климатик',
 'Паркомясто; Ново строителство',
 'Локал. отопление; Обзаведен; Асансьор; Ново строителство; Разрешено за дом. любимец; До метростанция - до 10 мин.пеш',
 'Ток; Водопровод; Ново строителство',
 'Необзаведен; Асансьор; Ново строителство; Лукс',
 'Ток; Водопровод; Канализация; ТЕЦ; Асансьор; Ново строителство',
 'Регулация; ВИЗА; Водопровод',
 'Обзаведен; Асансьор; До метростанция - до 10 мин.пеш',
 'Асансьор; Ново строителство; Лукс; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Ток; Водопровод; Ново строителство',
 'Локал. отопление; Климатик; Ток; Водопровод; Канализация; Асансьор; Ново строителство',
 'Необзаведен; WC; Асансьор; Двор; Ново строителство',
 'Телефон; Обзаведен; ТЕЦ; Асансьор; Лукс',
 'Климатик; Ток; Водопровод; Канализация; Асансьор; Ново строителство; Лукс',
 'Необзаведен; Паркомясто; Асансьор; Ново строителство',
 'Климатик; Паркомясто; Ток; Асансьор; Двор; Ново строителство; Лукс',
 'Климатик; Ток; Водопровод; Канализация',
 'Климатик',
 'Обзаведен; Двор',
 'Необзаведен; Водопровод; Канализация; WC; Асансьор; Ново строителство',
 'Интернет връзка; Паркомясто; До метростанция - до 10 мин.пеш',
 'Климатик; Асансьор',
 'Локал. отопление; Необзаведен; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс; До метростанция - до 10 мин.пеш',
 'Ток; Водопровод; Асансьор; Двор; Ново строителство',
 'Необзаведен; ТЕЦ; Гараж; Асансьор; Ново строителство; Паркомясто; До метростанция - до 10 мин.пеш',
 'Ток; Ново строителство',
 'Локал. отопление; Необзаведен; Асансьор; Ново строителство; Паркомясто; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Телефон; Климатик; WC; Предназначение; Ново строителство',
 'Локал. отопление; Телефон; Необзаведен; Климатик; Обезопасен; Интернет връзка; Ново строителство; Лукс',
 'Локал. отопление; Необзаведен; Климатик; Офис сграда; Интернет връзка; Гараж; Асансьор; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Климатик; Ток; Водопровод; Асансьор; Двор; Ново строителство; Лукс',
 'Необзаведен; Климатик; Ново строителство',
 'Локал. отопление; Необзаведен; Обезопасен; Ново строителство; До метростанция - до 10 мин.пеш',
 'Обзаведен; ТЕЦ; Асансьор; Ново строителство',
 'Ток; ТЕЦ; Гараж; Асансьор; Ново строителство',
 'Обзаведен; ТЕЦ; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс',
 'Климатик; Ток; Водопровод; Канализация; ТЕЦ; Асансьор; Ново строителство',
 'Ток; Водопровод; Канализация; Асансьор; Двор; Лукс',
 'Телефон; ТЕЦ; Асансьор; Ново строителство; Разрешено за дом. любимец; Паркомясто; Лукс; До метростанция - до 10 мин.пеш',
 'Необзаведен; Асансьор; До метростанция - до 10 мин.пеш',
 'Регулация; Ток; Канализация; Равен; За жилищно строителство; Подходящо за живеене',
 'Обзаведен; Асансьор; Паркомясто',
 'Климатик; Кухня; Склад; WC; Трифазен ток',
 'Обзаведен; Гараж; Асансьор; Паркомясто',
 'Локал. отопление; Телефон; Необзаведен; Гараж; Ново строителство; Паркомясто',
 'Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Ново строителство',
 'Регулация; Ток; Водопровод; Канализация; Равен; За промишлено строителство',
 'Равен; За жилищно строителство; За промишлено строителство',
 'Необзаведен; Асансьор; Ново строителство; Паркомясто',
 'Локал. отопление; Климатик; Ток; Асансьор; Ново строителство; Лукс',
 'Паркомясто; Ток; Водопровод; Канализация; Гараж; Ново строителство',
 'Локал. отопление; Необзаведен; Асансьор',
 'Локал. отопление; Необзаведен; Обзаведен; Обезопасен; Офис сграда; Ново строителство; До метростанция - до 10 мин.пеш',
 'Телефон; Необзаведен; ТЕЦ; Гараж; Асансьор; Ново строителство; Лукс',
 'Необзаведен; Склад; WC; Асансьор; Ново строителство',
 'Необзаведен; Асансьор; Подходящо за живеене',
 'Необзаведен; Паркомясто; Асансьор; Ново строителство; Подходящо за живеене',
 'Локал. отопление; Ново строителство',
 'Необзаведен; Климатик; Паркомясто; Асансьор; Ново строителство',
 'Регулация; ВИЗА; Ток; Водопровод; За жилищно строителство; Подходящо за живеене; На първа линия',
 'Обзаведен; Склад; Асансьор',
 'Климатик; Паркомясто; Ток; Водопровод; Канализация; Асансьор; Ново строителство',
 'Гараж; Асансьор; Ново строителство; Лукс',
 'Климатик; Ток; Водопровод; Канализация; Гараж; Асансьор; Ново строителство',
 'Ток; Водопровод; ТЕЦ; Асансьор; Ново строителство',
 'Регулация; Ток; За жилищно строителство',
 'Телефон; Обзаведен; Интернет връзка; ТЕЦ; До метростанция - до 10 мин.пеш',
 'Телефон; ТЕЦ; WC; Предназначение',
 'Регулация; ВИЗА; Равен; За жилищно строителство',
 'Интернет връзка; ТЕЦ; До метростанция - до 10 мин.пеш',
 'Регулация; Ток; Водопровод; Канализация; Равен; За жилищно строителство; Делим; Подходящо за живеене',
 'Климатик; ТЕЦ; WC; Предназначение',
 'Фризьорски салон; Козметичен салон',
 'Необзаведен; ТЕЦ; До метростанция - до 10 мин.пеш',
 'Необзаведен; WC; Асансьор; Ново строителство',
 'Локал. отопление; Необзаведен; Асансьор; Ново строителство; Разрешено за дом. любимец',
 'Гараж; Паркомясто',
 'Интернет връзка; Ток; Водопровод; Канализация; Гараж; Асансьор; Двор; Ново строителство',
 'Обзаведен; Климатик; Обезопасен; Офис сграда; Охрана; ТЕЦ; Асансьор; Ново строителство',
 'Необзаведен; Паркомясто; Гараж; Асансьор',
 'Интернет връзка; Паркомясто; Ток; Водопровод; Канализация; Асансьор; Двор; Ново строителство; Лукс',
 'Обзаведен; Гараж; Паркомясто',
 'Регулация; Ток; Водопровод; Канализация; Подходящо за живеене',
 'Обзаведен; Водопровод; ТЕЦ; Склад; Асансьор',
 'Регулация; ВИЗА; За жилищно строителство',
 'Климатик; Ток; Водопровод; ТЕЦ; Асансьор; Ново строителство; Лукс',
 'Необзаведен; ТЕЦ; Асансьор; Ново строителство; Разрешено за дом. любимец; Паркомясто; Лукс; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Ток; Водопровод; WC; Ново строителство',
 'Телефон',
 'Обзаведен; ТЕЦ; Лукс; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Климатик; Ток; Водопровод; Асансьор; Ново строителство; Лукс',
 'Обзаведен; Ток; Водопровод; Канализация; ТЕЦ; Склад; WC; Асансьор',
 'Регулация; Водопровод; Канализация; Равен; За жилищно строителство',
 'Телефон; Необзаведен; ТЕЦ; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс',
 'Локал. отопление; Ток; Водопровод; Канализация; Гараж; Ново строителство',
 'Телефон; Необзаведен; ТЕЦ; Асансьор; Ново строителство; Лукс; До метростанция - до 10 мин.пеш',
 'Локал. отопление; Телефон; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс',
 'Равен; За жилищно строителство',
 'Локал. отопление; Необзаведен; Двор; Разрешено за дом. любимец',
 'Паркомясто; Ток; Ново строителство; Лукс',
 'Необзаведен; Паркомясто; ТЕЦ; Асансьор',
 'Паркомясто; Ток; Водопровод; Канализация; Асансьор; Двор; Ново строителство; Лукс',
 'Климатик; Паркомясто; Ток; Водопровод; Гараж; Асансьор; Двор; Ново строителство; Лукс',
 'Обзаведен; Асансьор; Ново строителство; До метростанция - до 10 мин.пеш',
 'Интернет връзка; Ток; Водопровод; Канализация; ТЕЦ; Асансьор; Двор; Ново строителство',
 'Гараж',
 'Локал. отопление; Телефон; Обзаведен; Гараж; Асансьор; Ново строителство; Паркомясто; Лукс',
 'Необзаведен; Обзаведен; Двор; Ново строителство; Подходящо за живеене; Лукс',
 'Ток; Водопровод; Канализация; Асансьор; Лукс',
 'Локал. отопление; Необзаведен',
 'Обзаведен; Асансьор; Паркомясто; Лукс',
 'Обзаведен; Ток; Водопровод; Канализация; WC; Ново строителство; Лукс']

In [24]:
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch table info
cursor.execute("PRAGMA table_info('ads_raw')")
table_info = cursor.fetchall()

for col in table_info:
    print(col)

conn.close()

(0, 'hash_id', 'TEXT', 0, None, 1)
(1, 'title', 'TEXT', 0, None, 0)
(2, 'link', 'TEXT', 0, None, 0)
(3, 'price_m2_eur', 'TEXT', 0, None, 0)
(4, 'price_m2_bgn', 'TEXT', 0, None, 0)
(5, 'size_m2', 'TEXT', 0, None, 0)
(6, 'description', 'TEXT', 0, None, 0)
(7, 'floor', 'TEXT', 0, None, 0)
(8, 'akt16', 'TEXT', 0, None, 0)
(9, 'energy_class', 'TEXT', 0, None, 0)
(10, 'potreblenie', 'TEXT', 0, None, 0)
(11, 'broker_commision', 'TEXT', 0, None, 0)
(12, 'additional_notes', 'TEXT', 0, None, 0)
(13, 'status', 'TEXT', 0, "'pending'", 0)
(14, 'scraped_at', 'DATETIME', 0, None, 0)
(15, 'last_updated', 'DATETIME', 0, None, 0)

In [8]:
import sqlite3

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute("SELECT COUNT(*) FROM ads_raw WHERE status = 'done'")
pending = cursor.fetchall()
conn.close()
pending

# # Convert to list of dicts
# pending_list = [{"hash_id": row[0], "link": row[1]} for row in pending]

# # Or if you want column names from cursor.description
# columns = [desc[0] for desc in cursor.description]
# pending_list = [dict(zip(columns, row)) for row in pending]
# conn.close()
# pending_list

[(6221,)]

In [ ]:
import sqlite3

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute("SELECT COUNT(*) FROM ads_cleaned")
pending = cursor.fetchall()
conn.close()
pending

[(6221,)]

In [ ]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()

# Fetch all data
cursor.execute("SELECT * FROM ads_cleaned")
rows = cursor.fetchall()
columns = [description[0] for description in cursor.description]
conn.close()

ads_cleaned = pd.DataFrame(data=rows, columns=columns)
ads_cleaned

,hash_id,title,link,neighbourhood,type_of_estate,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,extras,total_price_eur
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Оборище,гараж,3333.0,6519.43,12.0,"Строително-инвестиционна компания Идея Хоум, п...",NaN,1.0,NaN,NaN,0.0,Посочената цена не включва местни данъци и такси.,ТЕЦ,39996.0
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,Банкя (гр.),парцел,78.0,152.78,896.0,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,NaN,1.0,Посочената цена не включва местни данъци и такси.,Регулация,69888.0
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,Гео Милев,магазин,2835.0,5545.72,31.0,"Dotwon Real Estate, част от Dotwon Group, пред...",0.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,,87885.0
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Овча Купел,жилище,1888.0,3692.13,49.0,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,1.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен; Паркомясто,92512.0
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Фондови Жилища,жилище,1745.0,3413.81,55.0,След основен ремонт. Едностаен апартамент в ту...,2.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,,95975.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6216,e7c20c29939aa363004c2b270277574739bf5775761580...,"Имот - продава Тристаен апартамент, в София, М...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Манастирски ливади Изток,жилище,2680.0,5241.01,111.0,"""Бориса Апартментс 2"" е затворен комплекс с мо...",1.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,EMPTY,297480.0
6217,5e859d392492ad71fb2ecdb32733badcc69b2bb2a84745...,"Имот - продава Тристаен апартамент, в София, Д...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Дружба 2,жилище,2361.0,4617.62,126.0,New Estates има удоволствието да представя про...,3.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен,297486.0
6218,766bd265e225f4db1bfeda0ba5f8b43fdea9782d92a21c...,"Имот - продава Тристаен апартамент, в София, Д...",https://www.imoti.net/bg/obiava/prodava--v-str...,Дружба 2,жилище,2380.0,4654.56,125.0,ЕРА Младост предлага БЕЗ КОМИСОННА! Двустайни ...,3.0,NaN,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен; Ток; Водопровод; Канализация; ТЕЦ...,297500.0
6219,d92ab7126b07222b7e5189b66cb79e91d7cad2812a0f8a...,"Имот - продава Тристаен апартамент, в София, П...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Панчарево (с.),жилище,2500.0,4889.58,119.0,ВИЖТЕ ВИДЕО ОТ ЗАСНЕМАНЕ С ДРОН: https://bit.l...,2.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Необзаведен; Гараж; Асансьор; Паркомясто,297500.0
6220,840664968bd39943642cda13e547101a157e36a5d5c9b7...,"Имот - продава Тристаен апартамент, в София, Х...",https://www.imoti.net/bg/obiava/prodava/sofia/...,Хладилника,жилище,2611.0,5107.46,114.0,ЕРА Младост продава апартамент в сграда с разр...,5.0,1.0,N/A,N/A,1.0,Посочената цена не включва местни данъци и такси.,Локал. отопление; Необзаведен; Ток; Водопровод...,297654.0

In [2]:
ads_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           6221 non-null   str
 1   title             6221 non-null   str
 2   link              6221 non-null   str
 3   neighbourhood     6110 non-null   str
 4   type_of_estate    6221 non-null   str
 5   price_m2_eur      6130 non-null   float64
 6   price_m2_bgn      6130 non-null   float64
 7   size_m2           6126 non-null   float64
 8   description       6221 non-null   str
 9   floor             5435 non-null   float64
 10  akt16             5276 non-null   float64
 11  energy_class      5574 non-null   str
 12  potreblenie       5574 non-null   str
 13  broker_commision  6106 non-null   float64
 14  additional_notes  6134 non-null   str
 15  extras            6221 non-null   str
dtypes: float64(6), str(10)
memory usage: 777.8 KB

In [4]:
import sqlite3

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute('''
SELECT
    price_m2_eur,
    size_m2,
    COALESCE(price_m2_eur,0) * COALESCE(size_m2,0) AS computed,
    total_price_eur
FROM ads_cleaned
WHERE total_price_eur IS NULL
LIMIT 20;
               ''')
pending = cursor.fetchall()
conn.close()
pending

[(3333, 12, 39996, None),
 (78, 896, 69888, None),
 (2835, 31, 87885, None),
 (1888, 49, 92512, None),
 (1745, 55, 95975, None),
 (1581, 62, 98022, None),
 (2240, 44, 98560, None),
 (1761, 56, 98616, None),
 (1768, 56, 99008, None),
 (1882, 61, 114802, None),
 (1761, 67, 117987, None),
 (3750, 32, 120000, None),
 (2711, 45, 121995, None),
 (1822, 68, 123896, None),
 (2723, 47, 127981, None),
 (1937, 67, 129779, None),
 (2007, 67, 134469, None),
 (2007, 68, 136476, None),
 (3537, 41, 145017, None),
 (2184, 68, 148512, None)]

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()

# List all tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
tables = cursor.fetchall()
conn.close()

print("Tables in database:")
for t in tables:
    print(" -", t[0])

Tables in database:
 - ads_cleaned
 - ads_raw

In [4]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()

# Get column info for a specific table — change table name as needed
table_name = 'ads_cleaned'
cursor.execute(f"PRAGMA table_info('{table_name}')")
col_info = cursor.fetchall()
conn.close()

df_cols = pd.DataFrame(col_info, columns=['cid', 'name', 'type', 'notnull', 'default_value', 'pk'])
print(f"Column info for '{table_name}':")
df_cols

Column info for 'ads_cleaned':

    cid              name            type  notnull default_value  pk
0     0           hash_id     VARCHAR(64)        0          None   1
1     1             title    VARCHAR(500)        0          None   0
2     2              link   VARCHAR(1000)        0          None   0
3     3     neighbourhood    VARCHAR(255)        0          None   0
4     4    type_of_estate    VARCHAR(100)        0          None   0
5     5      price_m2_eur   DECIMAL(10,2)        0          None   0
6     6      price_m2_bgn   DECIMAL(10,2)        0          None   0
7     7           size_m2   DECIMAL(10,2)        0          None   0
8     8       description            TEXT        0          None   0
9     9             floor        SMALLINT        0          None   0
10   10             akt16            BOOL        0          None   0
11   11      energy_class    VARCHAR(255)        0          None   0
12   12       potreblenie    VARCHAR(255)        0          None   0
13   13  broker_commision            BOOL        0          None   0
14   14  additional_notes   VARCHAR(1000)        0          None   0
15   15            extras    VARCHAR(500)        0          None   0
16   16   total_price_eur  DECIMAL(10, 2)        0          None   0